version: '3.8'

services:
  paradedb:
    image: paradedb/paradedb:latest
    environment:
      POSTGRES_DB: comp550-final
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"