# docker-compose.yml
version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: comp550-final
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data_injection_script.py:/data_injection_script.py
    ports:
      - "5432:5432"

volumes:
  db-data:
